# 공통 설정
server:
  port: 8080

spring:
  application:
    name: mr-patent
  
  # Profile 설정 - 기본값은 local 프로필 사용
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  
  # JPA 공통 설정
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  
  # Multipart 설정
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# JWT 설정
jwt:
  secret: whereareyouningmoforjwtdujmyssjsmyjmrpatentwithsldahgkdl208longlongvery
  access-token-expiration: 3600000 # 1시간
  refresh-token-expiration: 2592000000 # 30일

# 로깅 설정
logging:
  level:
    org:
      springframework:
        web: INFO